title: Class prerequisites
tagline: Meet all the prerequisites for an upcoming class
description: Meet all the prerequisites for an upcoming class
template:
  name: prerequisites
  repo: false
before:
# Create issue one for GitHub Pages
- type: createIssue
  title: Welcome
  body: welcome.md
- type: createIssue
  title: Supported browser
  body: browser.md

# Repo artifacts:
# 1. Issue: Welcome
# 2. Issue: Supported browser
# 3. Issue: Locate your shell
# 4. Issue: Install Git
# 5. Issue: Try a clone
# 6. Issue: Try a push
# 7. Issue: Pick a text editor

steps:

# 1
- title: Use a supported browser
  description: Use a supported browser
  event: issues
  actions:
  - type: gate
    left: '%payload.issue.title%'
    operator: ===
    right: Supported browser
  - type: gate
    gates:
    - left: '%payload.action%'
      operator: ===
      right: closed
    - left: '%payload.action%'
      operator: ===
      right: labeled
  - type: createIssue
    title: Locate your shell
    body: shell.md


# 2
- title: Locate your shell
  description: Locate your shell
  event: issues.closed
  actions:
  - type: gate
    left: '%payload.issue.title%'
    operator: ===
    right: Locate your shell
  - type: createIssue
    title: Install Git
    body: check-git.md

# 3
- title: Check for Git
  description: Check for Git
  event: issue_comment.created
  actions:
  - type: gate
    left: '%payload.issue.title%'
    operator: ===
    right: Install Git
  - type: gate
    left: '/[2-9]+\.\d+\.\d+/gm'
    operator: test
    right: '%payload.comment.body%'
    else:
    - type: respond
      with: no-version.md
  - type: respond
    with: version-success.md
  - type: createIssue
    title: Try a clone
    body: try-clone.md
    data:
      cloneURL: '%payload.repository.clone_url%'

# 4
- title: Clone the repository
  description: Clone the respository
  event: issue_comment.created
  actions:
  - type: gate
    gates:
    - left: '/You appear to have cloned an empty repository./gm'
      operator: test
      right: '%payload.comment.body%'
    - left: '/, done./gm'
      operator: test
      right: '%payload.comment.body%'
    else:
    - type: respond
      with: no-clone.md
  - type: createIssue
    title: Try a push
    body: push.md
  - type: respond
    with: cloned.md
  

# 5
- title: Push to the repository
  description: Push to the repository
  event: issue_comment.created
  actions:
  - type: gate
    left: '/completed with \d+ local objects./gm'
    operator: test
    right: '%payload.comment.body%'
    else:
    - type: respond
      with: proxy.md
  - type: respond
    with: pushed.md
  - type: createIssue
    title: Pick a text editor
    body: editor.md

# 6
- title: Use a recommended text editor
  description: Use a recommended text editor
  event: issues
  actions:
  - type: gate
    left: '%payload.action%'
    operator: ===
    right: edited
    else:
    - type: createIssue
      title: Congratulations
      body: congratulations.md
  - type: gate
    left: '/- \[x\] Atom/gm'
    operator: test
    right: '%payload.issue.body%'
    else:
    - type: gate
      left: '/- \[x\] Visual Studio Code/gm'
      operator: test
      right: '%payload.issue.body%'
    - type: respond
      with: vscode.md
  - type: respond
    with: atom.md
