title: Class prerequisites
tagline: Meet all the prerequisites for an upcoming class
description: Meet all the prerequisites for an upcoming class
template:
  name: prerequisites
  repo: scratch

before:
# Create issue one for GitHub Pages
- type: createIssue
  title: Welcome
  body: welcome.md
- type: createIssue
  title: Supported browser
  body: browser.md

# Repo artifacts:
# 1. Issue: Welcome
# 2. Issue: Supported browser

steps:

# 1
- title: Use a supported browser
  description: Use a supported browser
  event: issues
  actions:
  - type: gate
    left: '%payload.issue.title%'
    operator: ===
    right: Supported browser
  - type: gate
    gates:
    - left: '%payload.action%'
      operator: ===
      right: closed
    - left: '%payload.action%'
      operator: ===
      right: labeled
  - type: createIssue
    title: Locate your shell
    body: shell.md


# 2
- title: Locate your shell
  description: Locate your shell
  event: issues.edited
  actions:
  - type: gate
    left: '%payload.issue.title%'
    operator: ===
    right: Locate your shell
  - type: gate
    required: false
    left: '/^-\s\[x\]\sWindows$/gm'
    operator: test
    right: '%payload.issue.body%'
    else:
    - type: respond
      with: nix.md
  - type: respond
    with: windows.md

# 3
- title: Launch your shell
  description: Launch your shell
  event: issues.closed
  actions:
  - type: gate
    left: '%payload.issue.title%'
    operator: ===
    right: Locate your shell
  - type: createIssue
    title: Install Git
    body: check-git.md

# 4
- title: Check for Git
  description: Check for Git
  event: issue_comment.created
  actions:
  - type: gate
    left: '%payload.issue.title%'
    operator: ===
    right: Install Git
  - type: gate
    left: '/[2-9]+\.\d+\.\d+/gm'
    operator: test
    right: '%payload.comment.body%'
    else:
    - type: respond
      with: no-version.md
  - type: respond
    with: version-success.md